# Generated by Django 5.1.4 on 2025-01-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "goal_currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("EGP", "EGP")],
                        default="EGP",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INACTIVE", "Inactive"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("CLOSED", "Closed"),
                        ],
                        default="INACTIVE",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
