version: "3"

services:
  # web:
  #   build:
  #     context: .
  #   container_name: donation_django_app
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8004:8004"
  #   env_file:
  #     - .env.production
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    container_name: donation_postgres_db
    env_file:
      - .env.production
    ports:
      - "5435:5432"
    volumes:
      - donation_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
volumes:
  donation_postgres_data: {}
