version: "3"

services:
  web:
    build:
      context: .
    container_name: donation_django_app
    command: python manage.py runserver 0.0.0.0:8004
    volumes:
      - .:/app
    ports:
      - "8004:8004"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: donation_postgres_db
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_db
    ports:
      - "5434:5432"
    volumes:
      - donation_postgres_data:/var/lib/postgresql/data

volumes:
  donation_postgres_data: {}
