# Generated by Django 5.1.4 on 2025-01-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_permission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role",
                to="users.role",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(
                choices=[
                    ("can_view", "Can view"),
                    ("can_edit", "Can edit"),
                    ("can_delete", "Can delete"),
                    ("can_view", "Can view"),
                    ("can_donate", "Can donate"),
                    ("can_view", "Can view"),
                    ("can_create", "Can create"),
                    ("can_edit_campaign", "Can Edit Campaign"),
                    ("can_create_campaign", "Can Create Campaign"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("Admin", "ADMIN"),
                    ("Donar", "DONAR"),
                    ("Organizer", "ORGANIZER"),
                    ("Investor", "INVESTOR"),
                ],
                max_length=255,
            ),
        ),
    ]
