# Generated by Django 5.1.4 on 2025-01-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(
                choices=[
                    ("can_view", "Can view"),
                    ("can_edit", "Can edit"),
                    ("can_delete", "Can delete"),
                    ("can_view", "Can view"),
                    ("can_donate", "Can donate"),
                    ("can_view", "Can view"),
                    ("can_create", "Can create"),
                    ("can_edit_campaign", "Can Edit Campaign"),
                    ("can_create_campaign", "Can Create Campaign"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
