# Generated by Django 5.1.4 on 2025-02-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_remove_donation_currency_remove_donation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "pending"),
                    ("COMPLETED", "completed"),
                    ("FAILED", "failed"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
